---
- name: Install AWS CLI v2 using yum (Amazon Linux 2)
  hosts: g1
  become: true

  tasks:
    - name: Install dependencies (yum)
      yum:
        name:
          - curl
          - unzip
        state: present

    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Run AWS CLI installer
      command: /tmp/aws/install

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_cli_version
      changed_when: false

    - name: Show AWS CLI version
      debug:
        var: aws_cli_version.stdout
