---
- name: Deploy WAR file from S3 to Tomcat
  hosts: g1
  become: yes

  tasks:
    - name: Ensure /tmp directory exists
      file:
        path: /tmp
        state: directory

    - name: Download WAR file from S3
      shell: aws s3 cp s3://javacal12345/WebAppCal.0.0.1-SNAPSHOT.war /tmp/WebAppCal.0.0.1-SNAPSHOT.war
      args:
        warn: false

    - name: Copy WAR to Tomcat webapps
      copy:
        src: /tmp/WebAppCal.0.0.1-SNAPSHOT.war
        dest: /home/ec2-user/apache-tomcat-7.0.94/webapps/WebAppCal.0.0.1-SNAPSHOT.war
        remote_src: yes
