---
- name: Install and start Tomcat on all g1 servers
  hosts: g1
  become: true

  vars:
    tomcat_version: 9.0.85
    tomcat_user: tomcat
    install_dir: /opt/tomcat

  tasks:

    - name: Install Java
      yum:
        name: java-11-openjdk
        state: present

    - name: Create Tomcat user
      user:
        name: "{{ tomcat_user }}"
        shell: /bin/false

    - name: Download Tomcat archive
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp/apache-tomcat.tar.gz

    - name: Create Tomcat install directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: "{{ install_dir }}"
        remote_src: yes
        creates: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Symlink to tomcat
      file:
        src: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ install_dir }}/latest"
        state: link
        force: yes

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_user }}

          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_PID={{ install_dir }}/latest/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ install_dir }}/latest"
          Environment="CATALINA_BASE={{ install_dir }}/latest"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

          ExecStart={{ install_dir }}/latest/bin/startup.sh
          ExecStop={{ install_dir }}/latest/bin/shutdown.sh

          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started
